name: Validate PRs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Check go mod status
      run: |
        go mod tidy
        if [[ ! -z $(git status -s) ]]
        then
          echo "Go mod state is not clean"
          exit 1
        fi
    - name: Build main
      run: go build main.go
    
    # Commenting tests untill tests are fixed, mentioned in Issue#18
    #- name: Run Go Tests
    #  run: go test ./...

    - name: Check format
      run: |
        go fmt -x ./...
        if [[ ! -z $(git status -s) ]]
        then
          echo "not well formatted sources are found"
          exit 1
        fi

